mod desktop;

use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            app.manage(desktop::DesktopState::initialize(app.handle())?);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            desktop::commands::desktop_get_session,
            desktop::commands::desktop_get_runtime_status,
            desktop::commands::desktop_get_bootstrap_status,
            desktop::commands::desktop_bootstrap_superadmin,
            desktop::commands::desktop_check_bootstrap_database,
            desktop::commands::desktop_link_bootstrap_database,
            desktop::commands::desktop_login,
            desktop::commands::desktop_logout,
            desktop::commands::desktop_get_master_operators,
            desktop::commands::desktop_create_operator,
            desktop::commands::desktop_update_operator,
            desktop::commands::desktop_delete_operator,
            desktop::commands::desktop_get_roles,
            desktop::commands::desktop_create_role,
            desktop::commands::desktop_update_role,
            desktop::commands::desktop_set_role_permissions,
            desktop::commands::desktop_delete_role,
            desktop::commands::desktop_get_employees,
            desktop::commands::desktop_create_employee,
            desktop::commands::desktop_import_employees,
            desktop::commands::desktop_update_employee,
            desktop::commands::desktop_set_employee_status,
            desktop::commands::desktop_generate_employee_tokens,
            desktop::commands::desktop_get_shifts,
            desktop::commands::desktop_create_shift,
            desktop::commands::desktop_update_shift,
            desktop::commands::desktop_delete_shift,
            desktop::commands::desktop_submit_qr_scan,
            desktop::commands::desktop_get_corrections,
            desktop::commands::desktop_create_correction,
            desktop::commands::desktop_delete_correction,
            desktop::commands::desktop_update_attendance,
            desktop::commands::desktop_delete_attendance,
            desktop::commands::desktop_delete_log_scan,
            desktop::commands::desktop_delete_import_offline,
            desktop::commands::desktop_get_backups,
            desktop::commands::desktop_create_backup,
            desktop::commands::desktop_cancel_backup,
            desktop::commands::desktop_get_imports,
            desktop::commands::desktop_import_offline,
            desktop::commands::desktop_get_dashboard_data,
            desktop::commands::desktop_get_id_cards,
            desktop::commands::desktop_update_id_card,
            desktop::commands::desktop_get_geofence_settings,
            desktop::commands::desktop_update_geofence_settings,
            desktop::commands::desktop_get_scanner_settings,
            desktop::commands::desktop_update_scanner_settings,
            desktop::commands::desktop_get_sync_status,
            desktop::commands::desktop_sync_now,
            desktop::commands::desktop_get_sync_conflicts,
            desktop::commands::desktop_retry_failed_sync,
            desktop::commands::desktop_resolve_sync_conflicts,
            desktop::commands::desktop_resolve_sync_conflicts_local,
            desktop::commands::desktop_clear_failed_sync,
            desktop::commands::desktop_save_file,
            desktop::commands::desktop_get_holidays,
            desktop::commands::desktop_create_holiday,
            desktop::commands::desktop_update_holiday,
            desktop::commands::desktop_delete_holiday,
            desktop::commands::desktop_get_alfa_settings,
            desktop::commands::desktop_save_alfa_settings,
            desktop::commands::desktop_trigger_generate_alfa,
            desktop::commands::desktop_get_server_url,
            desktop::commands::desktop_set_server_url,
            desktop::commands::desktop_get_company_profile,
            desktop::commands::desktop_update_company_profile,
            desktop::commands::desktop_get_id_card_template,
            desktop::commands::desktop_save_id_card_template,
            desktop::commands::desktop_force_resync_settings,
            desktop::commands::desktop_debug_template_sync,
            desktop::commands::desktop_get_turso_url,
            desktop::commands::desktop_get_database_config,
            desktop::commands::desktop_save_turso_config,
            desktop::commands::desktop_test_turso_connection,
            desktop::commands::desktop_clear_turso_config,
            desktop::payroll::commands::desktop_get_salary_configs,
            desktop::payroll::commands::desktop_save_salary_config,
            desktop::payroll::commands::desktop_delete_salary_config,
            desktop::payroll::commands::desktop_get_overtime_rules,
            desktop::payroll::commands::desktop_save_overtime_rule,
            desktop::payroll::commands::desktop_delete_overtime_rule,
            desktop::payroll::commands::desktop_save_overtime_rules,
            desktop::payroll::commands::desktop_get_payroll_components,
            desktop::payroll::commands::desktop_save_payroll_component,
            desktop::payroll::commands::desktop_delete_payroll_component,
            desktop::payroll::commands::desktop_get_tax_rules,
            desktop::payroll::commands::desktop_save_tax_rule,
            desktop::payroll::commands::desktop_delete_tax_rule,
            desktop::payroll::commands::desktop_save_tax_rules,
            desktop::payroll::commands::desktop_get_bpjs_rules,
            desktop::payroll::commands::desktop_save_bpjs_rule,
            desktop::payroll::commands::desktop_delete_bpjs_rule,
            desktop::payroll::commands::desktop_save_bpjs_rules,
            desktop::payroll::commands::desktop_get_payroll_recap,
            desktop::payroll::commands::desktop_create_payroll_run,
            desktop::payroll::commands::desktop_list_payroll_runs,
            desktop::payroll::commands::desktop_get_payroll_run_detail,
            desktop::payroll::commands::desktop_transition_payroll_status,
        ])
        .run(tauri::generate_context!())
        .unwrap_or_else(|error| {
            eprintln!("Aplikasi Desktop berhenti karena runtime Tauri gagal: {error}");
            std::process::exit(1);
        });
}
